version: '3'
services:

  service_nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
      express_redis:
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "${APP_PORT}:${APP_PORT}"

networks:
  express_redis:
